name: CI
on: push

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

  build:
    name: build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: go build ./cmd/chip8

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: golangci/golangci-lint-action@v2
        with:
          version: 1.34
          skip-go-installation: true

  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: go test -v -coverprofile coverage.txt -covermode=atomic ./...
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
